version: "3.8"

services:
  app:
    container_name: restaurant_app
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: >
      sh -c "python3 manage.py wait_for_db &&
             python3 manage.py makemigrations &&
             python3 manage.py migrate &&
             python3 manage.py runserver 0.0.0.0:8000"
    # env_file:
    #   - app/.env
    depends_on:
      - db

  celery:
    restart: always
    build:
      context: .
      args:
        - DEV=true
    command: celery -A app worker --loglevel=INFO
    # env_file:
    #   - app/.env
    volumes:
      - ./app:/app
    depends_on:
      - app
      - redis
      - db

  db:
    image: postgres:14-alpine
    container_name: pgdb-restaurant
    environment:
      - POSTGRES_DB=${{secrets.DB_NAME}}
      - POSTGRES_USER=${{secrets.DB_USER}}
      - POSTGRES_PASSWORD=${{secrets.DB_PASSWORD}}
      
  redis:
    image: redis:alpine
    ports:
    - "6379:6379"
