# Generated by Django 4.0.3 on 2022-05-20 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_cuisine_drink_ingredient_meal_tag_restaurant_order_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='avg_preparation_time',
            new_name='avg_delivery_time',
        ),
    ]
