# Generated by Django 4.0.3 on 2022-05-20 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_avg_preparation_time_restaurant_avg_delivery_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='restaurant_name',
            new_name='restaurant',
        ),
    ]
