# Generated by Django 4.0.3 on 2022-05-25 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='meals',
        ),
        migrations.RemoveField(
            model_name='order',
            name='meals',
        ),
        migrations.AddField(
            model_name='meal',
            name='menu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='core.menu'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tag'),
        ),
    ]
