# Generated by Django 4.0.3 on 2022-05-25 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_menu_meals_remove_order_meals_meal_menu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='core.menu'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.tag'),
        ),
    ]
