# Generated by Django 4.0.3 on 2022-05-25 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_meal_menu_alter_meal_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='menu',
        ),
        migrations.AddField(
            model_name='menu',
            name='meals',
            field=models.ManyToManyField(to='core.meal'),
        ),
    ]
