# Generated by Django 4.0.3 on 2022-06-09 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_restaurant_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='slug',
        ),
    ]
