---
name: Checks
 
on: [push]

env:
  SECRET_KEY: ${{ secrets.SECRET_KEY }} 
  DEBUG: ${{ secrets.DEBUG }}
  # NAME: os.environ.get('DB_NAME'),
  # USER: os.environ.get('DB_USER'),
  # PASSWORD: os.environ.get('DB_PASSWORD'),
  # HOST: os.environ.get('DB_HOST'),

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: docker-compose run --rm app sh -c "python manage.py test" 
      - name: Lint
        run: docker-compose run --rm app sh -c "flake8"