---
name: Checks
 
on: [push]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create env file
        env:
          SECRET_KEY: ${{secrets.SECRET_KEY}}
          DEBUG: ${{secrets.DEBUG}}
          DB_NAME: ${{secrets.DB_NAME}}
          DB_HOST: ${{secrets.DB_HOST}}
          DB_USER: ${{secrets.DB_USER}}
          DB_PASSWORD: ${{secrets.DB_PASSWORD}}
        run: |
          touch app/.env
          echo SECRET_KEY="$SECRET_KEY" >> app/.env
          echo DEBUG="$DEBUG" >> app/.env
          echo DB_NAME=$DB_NAME >> app/.env
          echo DB_HOST=$DB_HOST >> app/.env
          echo DB_USER=$DB_USER >> app/.env
          echo DB_PASSWORD=$DB_PASSWORD >> app/.env
      - name: Test
        run: |
          docker-compose --env-file app/.env up -d&& 
          docker-compose --env-file app/.env run --rm app sh -c "python3 manage.py wait_for_db && python3 manage.py test restaurant order"
      - name: Lint
        run: docker-compose run --rm app sh -c "flake8"
