---
name: Checks
 
on: [push]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create env file
        env:
          SECRETS: ${{secrets.TEST123}}
        run: |
          printf ${{env.SECRETS}} >> app/.env
          cat app/.env
